# Generated by Django 3.1.2 on 2020-10-16 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('creador', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('cod', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
