# Generated by Django 3.1.2 on 2020-11-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cod',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
